### PR TITLE
Load c code as python extension

### PR DESCRIPTION
**Pull request by il-katta**
Load c code as python extension for easing package creation and distribution

### CODE REVIEW

**Comment by morrolinux** [comment]
Cool, I haven't tested it yet but it's looking good.
Is it ready to be merged?

**Comment by il-katta** [comment]
il makefile continua ad essere rotto ma per altri motivi. 
si potrebbe modificare per utilizzare python setup.py e pip per installare gli eseguibili ma dovrebbe continuare a funzionare anhe così.
La modifica sarebbe una soluzione più robusta.

**Comment by il-katta** [comment]
tested on Ubuntu and Arch Linux, updated Makefile and documentation

**Comment by morrolinux** [comment]
What I tried:
```
python3 setup.py sdist
pip install .
sudo pacman -S libx11 python-pip make gcc xorg-xrandr
make install
```
What I got:
```
  File "/home/morro/.local/bin/i3expod.py", line 18, in <module>
    import prtscn
ImportError: dynamic module does not define module export function (PyInit_prtscn)
```

**Comment by il-katta** [comment]
umh. yeah, you probably have ad old prtscn.so file in /home/morro/.local/bin/.
try do delete it and run it again.
this can be a problem...

**Comment by il-katta** [comment]
brutal solution

**Comment by morrolinux** [comment]
I see you keep adding commits so I'm struggling a bit to understand when/if you're done.
Can I test it now? :)

**Comment by il-katta** [comment]
Yes, I solved the problem with previous installation files. meanwhile i also find a bug in the new code ( fixed with the last commit).
( ah, sorry for the forced push. my bad -.-' ) 
I think that now is fine.
Let me known.

**Pull request merged**
